#
# This is a generated file
#
platforms:
  - &defaults
    environment:
      - GRADLE_OPTS: -Dorg.gradle.daemon=false
      - JAVA_TOOL_OPTIONS: -XX:MaxRAM=4g -XX:ParallelGCThreads=2

  - &java8
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk
    
  - &java11
    <<: *defaults
    docker:
      - image: circleci/openjdk:11-jdk
    
caches:
  workspace:
    - &persist-workspace
      persist_to_workspace:
        root: .
        paths: .
    - &attach-workspace
      attach_workspace:
        at: .
  test_results:
    - &store-test-results
      store_test_results:
        paths: build/test-results/
  dependencies:

    - &save-gradle-dependencies-java8
      save_cache:
        name: Saving Gradle dependencies
        key: v3-gradle-java8-{{ checksum "build.gradle.kts" }}
        paths:
          - ~/.gradle/caches/modules-2/
    - &restore-gradle-dependencies-java8
      restore_cache:
        name: Restoring Gradle dependencies
        keys:
          - v3-gradle-java8-{{ checksum "build.gradle.kts" }}
    
    - &save-gradle-dependencies-java11
      save_cache:
        name: Saving Gradle dependencies
        key: v3-gradle-java11-{{ checksum "build.gradle.kts" }}
        paths:
          - ~/.gradle/caches/modules-2/
    - &restore-gradle-dependencies-java11
      restore_cache:
        name: Restoring Gradle dependencies
        keys:
          - v3-gradle-java11-{{ checksum "build.gradle.kts" }}
    
  wrapper:

    - &save-gradle-wrapper-current
      save_cache:
        name: Saving Gradle wrapper 4.10.2
        key: v2-gradle-wrapper-4.10.2
        paths:
          - ~/.gradle/wrapper/dists/gradle-4.10.2-bin/
          - ~/.gradle/caches/4.10.2/generated-gradle-jars/
          - ~/.gradle/notifications/4.10.2/
    - &restore-gradle-wrapper-current
      restore_cache:
        name: Restoring Gradle wrapper 4.10.2
        keys:
          - v2-gradle-wrapper-4.10.2
    
version: 2
jobs:
  checkout_code:
    <<: *java8
    steps:
      - checkout
      - run:
          name: Remove Git tracking files (reduces workspace size)
          command: rm -rf .git/
      - *persist-workspace

  java8:
    <<: *java8
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java8
      - *restore-gradle-wrapper-current
      - run:
          name: Build
          command: ./gradlew build
      - *store-test-results
      - *save-gradle-wrapper-current
      - *save-gradle-dependencies-java8
      - *persist-workspace
    
  java11:
    <<: *java11
    steps:
      - *attach-workspace
      - *restore-gradle-dependencies-java11
      - *restore-gradle-wrapper-current
      - run:
          name: Build
          command: ./gradlew build
      - *store-test-results
      - *save-gradle-wrapper-current
      - *save-gradle-dependencies-java11
      - *persist-workspace
    
workflows:
  version: 2
  tests:
    jobs:
      - checkout_code

      - java8:
          requires:
            - checkout_code
    
      - java11:
          requires:
            - java8