name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and Publish
        env:
          PGP_SIGNING_KEY: ${{ secrets.PGP_SIGNING_KEY }}
        run: ./gradlew --console=plain -PMAVEN_UPLOAD_USER="${{ secrets.SONATYPE_USER }}" -PMAVEN_UPLOAD_PWD="${{ secrets.SONATYPE_PASSWORD }}" -PPGP_SIGNING_PASSWORD="${{ secrets.PGP_SIGNING_PASSWORD }}" build publish
